# Generated by Django 4.0.6 on 2022-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='finish_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='finish_date',
            field=models.IntegerField(default=0),
        ),
    ]
