# Generated by Django 4.0.6 on 2022-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_education_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
