# Generated by Django 4.0.6 on 2022-07-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(help_text='İsim', max_length=30)),
                ('author_last_name', models.CharField(help_text='Soyisim', max_length=30)),
                ('comment_date', models.DateField(help_text='Tarih')),
                ('photo', models.ImageField(default='person_image/default.png', upload_to='person_image')),
                ('score', models.SmallIntegerField(help_text='Puan')),
                ('comment', models.CharField(help_text='Yorum', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='instruction_photo_1',
            field=models.ImageField(default='service_image/default.png', upload_to='service_image'),
        ),
        migrations.AddField(
            model_name='service',
            name='instruction_photo_1_visible',
            field=models.BooleanField(default=False, help_text='Fotoğraf 1 gözüksün mü?'),
        ),
        migrations.AddField(
            model_name='service',
            name='instruction_photo_2',
            field=models.ImageField(default='service_image/default.png', upload_to='service_image'),
        ),
        migrations.AddField(
            model_name='service',
            name='instruction_photo_2_visible',
            field=models.BooleanField(default=False, help_text='Fotoğraf 2 gözüksün mü?'),
        ),
        migrations.AddField(
            model_name='service',
            name='instruction_photo_3',
            field=models.ImageField(default='service_image/default.png', upload_to='service_image'),
        ),
        migrations.AddField(
            model_name='service',
            name='instruction_photo_3_visible',
            field=models.BooleanField(default=False, help_text='Fotoğraf 3 gözüksün mü?'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_year',
            field=models.IntegerField(default=0, help_text='Veriliş tarihi'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='educator_name',
            field=models.CharField(blank=True, default='', help_text='Eğitmen adı/yeri', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(help_text='Sertifikat adı', max_length=80),
        ),
        migrations.AlterField(
            model_name='clinicalapplications',
            name='name',
            field=models.CharField(help_text='Uygulama adı', max_length=80),
        ),
        migrations.AlterField(
            model_name='education',
            name='finish_date',
            field=models.IntegerField(default=0, help_text='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_department_name',
            field=models.CharField(help_text='Bölüm Adı', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(help_text='Okul Adı', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(default=0, help_text='Başlangıç tarihi'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='business_name',
            field=models.CharField(help_text='İş yerinin adı', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='finish_date',
            field=models.IntegerField(default=0, help_text='Bitiş tarihi'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='position',
            field=models.CharField(help_text='Pozisyon', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='start_date',
            field=models.IntegerField(default=0, help_text='Başlangıç tarihi'),
        ),
        migrations.AlterField(
            model_name='language',
            name='abbreviated_name',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='İsim', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='lang',
            field=models.ForeignKey(default=1, help_text='Hangi dile sahip üyelerde gözükeceğini belirler', on_delete=django.db.models.deletion.DO_NOTHING, to='home.language'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Soyisim', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(help_text='Pozisyon', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='brief',
            field=models.CharField(help_text='Kısa özet', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='instruction',
            field=models.CharField(help_text='Detaylı açıklama', max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='lang',
            field=models.ForeignKey(default=1, help_text='Hangi dile sahip üyelerde gözükeceğini belirler', on_delete=django.db.models.deletion.DO_NOTHING, to='home.language'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Servis adı', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='show_home_screen',
            field=models.BooleanField(default=False, help_text='Ana ekranda gözüksün mü?'),
        ),
    ]
