# Generated by Django 4.0.6 on 2022-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_service_instruction_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.SmallIntegerField(help_text='Puan', max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='instruction',
            field=models.TextField(),
        ),
    ]
