# Generated by Django 4.0.6 on 2022-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_score_alter_service_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(help_text='Puan', max_length=3),
        ),
    ]
