# Generated by Django 4.0.6 on 2022-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.SmallIntegerField(help_text='Puan'),
        ),
    ]
