# Generated by Django 4.0.6 on 2022-07-23 21:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='instruction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
