# Generated by Django 4.0.6 on 2022-07-24 10:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_service_instruction_photo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=250)),
                ('href', models.CharField(help_text='Tıklanıldığında açılacak site konumu', max_length=250)),
                ('photo', models.ImageField(default='slide_image/default.png', upload_to='slide_image')),
                ('slide_desc', ckeditor.fields.RichTextField()),
                ('lang', models.ForeignKey(default=1, help_text='Hangi dile sahip üyelerde gözükeceğini belirler', on_delete=django.db.models.deletion.DO_NOTHING, to='home.language')),
            ],
        ),
    ]
