# Generated by Django 4.0.6 on 2022-07-24 17:03

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homescreenslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='homescreenslide',
            name='is_google',
            field=models.BooleanField(default=False, help_text="Google'dan gelen mesaj mi?"),
        ),
        migrations.AddField(
            model_name='homescreenslide',
            name='show_home_page',
            field=models.BooleanField(default=True, help_text='Ana sayfa da gösterilsin mi?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Puan', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='homescreenslide',
            name='href',
            field=models.CharField(blank=True, help_text='Tıklanıldığında açılacak site konumu', max_length=250),
        ),
        migrations.AlterField(
            model_name='homescreenslide',
            name='photo',
            field=models.ImageField(default='home_slide_image/default.png', upload_to='home_slide_image'),
        ),
        migrations.AlterField(
            model_name='homescreenslide',
            name='slide_desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='brief',
            field=models.TextField(),
        ),
    ]
