# Generated by Django 4.0.6 on 2022-07-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homescreenslide_is_google_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_google',
            new_name='is_google_comment',
        ),
    ]
