# Generated by Django 4.0.6 on 2022-07-25 19:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_is_google_comment_is_google_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=250)),
                ('gallery_desc', ckeditor.fields.RichTextField(blank=True)),
                ('photo', models.ImageField(default='gallery/default.png', upload_to='gallery')),
                ('lang', models.ForeignKey(default=1, help_text='Hangi dile sahip üyelerde gözükeceğini belirler', on_delete=django.db.models.deletion.DO_NOTHING, to='home.language')),
            ],
        ),
    ]
