# Generated by Django 4.0.6 on 2022-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='show_home_screen',
        ),
        migrations.AddField(
            model_name='gallery',
            name='show_home_page',
            field=models.BooleanField(default=True, help_text='Ana sayfa da gösterilsin mi?'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_home_page',
            field=models.BooleanField(default=True, help_text='Ana sayfa da gösterilsin mi?'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(max_length=50),
        ),
    ]
